export const ICON_NAME = {
    FACEBOOK: 'FACEBOOK',
    FACEBOOK_ROUNDED: 'FACEBOOK_ROUNDED',
    YOUTUBE: 'YOUTUBE',
    INSTAGRAM: 'INSTAGRAM',
    SEND_ROUNDED: 'SEND_ROUNDED',
    PHONE_ANDROID: 'PHONE_ANDROID',
    MAIL_OUTLINED: 'MAIL_OUTLINED',
    LOCATION_OUTLINED: 'LOCATION_OUTLINED',
    ACCESS_TIME_OUTLINED: 'ACCESS_TIME_OUTLINED'
}