export const ICON_NAME = {
    FACEBOOK: 'FACEBOOK',
    YOUTUBE: 'YOUTUBE',
    INSTAGRAM: 'INSTAGRAM',
    MESSENGER: 'MESSENGER',
    CHEVRON_LEFT: 'CHEVRON_LEFT',
    CHEVRON_RIGHT: 'CHEVRON_RIGHT',
    PHONE_ANDROID: 'PHONE_ANDROID',
    ROUNDED: {
        SEND: 'SEND_ROUNDED',
        FACEBOOK: 'FACEBOOK_ROUNDED',
        ARROW_LEFT: 'ARROW_LEFT_ROUNDED',
        ARROW_RIGHT: 'ARROW_RIGHT_ROUNDED'
    },
    OUTLINED: {
        MAIL: 'MAIL_OUTLINED',
        LOCATION: 'LOCATION_OUTLINED',
        ACCESS_TIME: 'ACCESS_TIME_OUTLINED',
    },
    FEATHER: {
        HELP_CIRCLE: 'HELP_CIRCLE',
        SMARTPHONE: 'SMARTPHONE',
        USER: 'USER',
        SEARCH: 'SEARCH',
        HEART: 'HEART',
        SHOPPING_BAG: 'SHOPPING_BAG',
        MENU: 'MENU',
        X: 'X',
    }
}