export { default as ExamplePage } from "./example/example.page";
export { default as HomePage } from "./home/home.page";
export { default as LoginPage } from "./login/login.page";
export { default as UserProfilePage } from "./user-profile/user-profile.page";
export { default as ProductDetailPage } from "./product-detail/product-detail.page";
export { default as ProductListPage } from "./product-list/product-list.page";
export { default as CartPage } from "./cart/cart.page";
export { default as PaymentPage } from "./payment/payment.page";
export { default as BlogPage } from "./blog/blog.page";
